### ISSUE TITLE
Take advantage of defer and async

### ISSUE THREAD

**Issue by gmarty** [arcturus/gulp-sww#2]
Because the injected script is completely independent of all other potential JS scripts, we can take advantage of the `defer` and `async` attributes of the `<script>` tag.
So the injected tag would look like:

``` html
<script defer async src="install-sw.js"></script>
```

**Comment by gmarty** [comment]
Also as discussed offline, it may be more efficient to append the tag just after the `<html>` tag.

**Comment by arcturus** [comment]
Closed by #3
