### ISSUE TITLE
Fall back to app cache on non supporting browsers

### ISSUE THREAD

**Issue by gmarty** [arcturus/gulp-sww#5]
Let's make this Gulp task all about caching! We'll fall back to app cache if the service workers are not supported on the browser.

I'm opening this issue to keep a track of it but I'm also starting to implement it now.

**Comment by arcturus** [comment]
You rock! 🎱 \o/

**Comment by gmarty** [comment]
Closed as per https://github.com/arcturus/gulp-sww/commit/1e804cda44aa63eaca5e4b3d476d680c5bbd452c.
